Repository brain-tec/account-financial-tools, pull requests merged in 2021-08, with the labels that each got.

#661 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_batch_compute/i18n/fr.po
  account_asset_management/i18n/fr.po
  account_chart_update/i18n/fr.po
  account_check_deposit/i18n/fr.po
  account_cost_center/i18n/fr.po
  account_fiscal_month/i18n/fr.po
  account_fiscal_position_vat_check/i18n/fr.po
  account_fiscal_year_auto_create/i18n/fr.po
  account_group_menu/i18n/fr.po
  account_invoice_constraint_chronology/i18n/fr.po
  account_journal_lock_date/i18n/fr.po
  account_lock_date_update/i18n/fr.po
  account_move_batch_validate/i18n/fr.po
  account_move_budget/i18n/fr.po
  account_move_fiscal_month/i18n/fr.po
  account_move_fiscal_year/i18n/fr.po
  account_move_line_purchase_info/i18n/fr.po
  account_move_template/i18n/fr.po
  account_netting/i18n/fr.po
  account_partner_required/i18n/fr.po
  account_permanent_lock_move/i18n/fr.po
  account_renumber/i18n/fr.po
  account_spread_cost_revenue/i18n/fr.po
Labels: 12.0

#662 Syncing from upstream OCA/account-financial-tools (13.0)
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/readme/CONTRIBUTORS.rst
  account_move_print/readme/DESCRIPTION.rst
  account_move_print/readme/USAGE.rst
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_print/odoo/addons/account_move_print
  setup/account_move_print/setup.py
Labels: 13.0

#663 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/i18n/fr.po
  account_chart_update/i18n/fr.po
  account_cost_center/i18n/fr.po
  account_fiscal_position_vat_check/i18n/fr.po
  account_invoice_currency/i18n/fr.po
  account_loan/i18n/fr.po
  account_move_line_purchase_info/i18n/fr.po
  account_renumber/i18n/fr.po
  account_spread_cost_revenue/i18n/fr.po
Labels: 12.0

#664 Syncing from upstream OCA/account-financial-tools (14.0)
  account_move_force_removal/tests/test_move.py
Labels: 14.0

#665 Syncing from upstream OCA/account-financial-tools (12.0)
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/models/account_invoice_line.py
Labels: 12.0

#666 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/i18n/fr.po
Labels: 12.0

#667 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/README.rst
  account_menu/__manifest__.py
  account_menu/static/description/index.html
Labels: 14.0

#668 [t124146] Migration of account document reversal to v13
  account_document_reversal/__init__.py
  account_document_reversal/__manifest__.py
  account_document_reversal/i18n/account_document_reversal.pot
  account_document_reversal/i18n/hr.po
  account_document_reversal/i18n/pt.po
  account_document_reversal/models/__init__.py
  account_document_reversal/models/account.py
  account_document_reversal/models/account_bank_statement.py
  account_document_reversal/models/account_document_reversal.py
  account_document_reversal/models/account_move.py
  account_document_reversal/models/account_payment.py
  account_document_reversal/models/purchase.py
  account_document_reversal/models/sale.py
  account_document_reversal/readme/CONFIGURE.rst
  account_document_reversal/readme/CONTRIBUTORS.rst
  account_document_reversal/readme/DESCRIPTION.rst
  account_document_reversal/readme/USAGE.rst
  account_document_reversal/static/description/icon.png
  account_document_reversal/static/description/index.html
  account_document_reversal/tests/__init__.py
  account_document_reversal/tests/test_invoice_reversal.py
  account_document_reversal/tests/test_payment_reversal.py
  account_document_reversal/views/account_move_view.xml
  account_document_reversal/views/account_payment_view.xml
  account_document_reversal/views/account_view.xml
  account_document_reversal/wizard/__init__.py
  account_document_reversal/wizard/reverse_account_document.py
  account_document_reversal/wizard/reverse_account_document_wizard.xml
  setup/account_document_reversal/odoo/addons/account_document_reversal
  setup/account_document_reversal/setup.py
Labels: odoo_migration, 13.0.project_mi_465

#670 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/wizard/account_asset_remove.py
Labels: 14.0

#671 Syncing from upstream OCA/account-financial-tools (13.0)
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 13.0

#672 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 14.0

#673 Syncing from upstream OCA/account-financial-tools (8.0)
  README.md
Labels: 8.0

#674 Syncing from upstream OCA/account-financial-tools (9.0)
  README.md
Labels: 9.0

#675 Syncing from upstream OCA/account-financial-tools (10.0)
  README.md
Labels: 10.0

#676 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
Labels: 14.0

#677 Syncing from upstream OCA/account-financial-tools (13.0)
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/views/account_move_view.xml
Labels: 13.0

#678 Syncing from upstream OCA/account-financial-tools (13.0)
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/views/account_move_view.xml
Labels: 13.0

#679 Syncing from upstream OCA/account-financial-tools (12.0)
  account_tag_menu/i18n/tr.po
Labels: 12.0
