Repository brain-tec/account-financial-tools, pull requests merged in 2021-10, with the labels that each got.

#696 Syncing from upstream OCA/account-financial-tools (13.0)
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/migrations/13.0.1.0.0/post-migration.py
  account_spread_cost_revenue/migrations/13.0.1.0.0/pre-migration.py
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/CREDITS.rst
  account_spread_cost_revenue/readme/DESCRIPTION.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/static/src/js/account_spread.js
  account_spread_cost_revenue/static/src/scss/account_spread.scss
  account_spread_cost_revenue/templates/assets.xml
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_spread_cost_revenue/odoo/addons/account_spread_cost_revenue
  setup/account_spread_cost_revenue/setup.py
Labels: 13.0

#698 Merging 13.0 into 13.0.project_MI_465
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move.py
  account_maturity_date_default/tests/test_account_move.py
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/migrations/13.0.1.0.0/post-migration.py
  account_spread_cost_revenue/migrations/13.0.1.0.0/pre-migration.py
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/CREDITS.rst
  account_spread_cost_revenue/readme/DESCRIPTION.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/static/src/js/account_spread.js
  account_spread_cost_revenue/static/src/scss/account_spread.scss
  account_spread_cost_revenue/templates/assets.xml
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_spread_cost_revenue/odoo/addons/account_spread_cost_revenue
  setup/account_spread_cost_revenue/setup.py
Labels: 13.0.project_mi_465

#704 Syncing from upstream OCA/account-financial-tools (8.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 8.0

#705 Syncing from upstream OCA/account-financial-tools (9.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 9.0

#706 Syncing from upstream OCA/account-financial-tools (10.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 10.0

#707 Syncing from upstream OCA/account-financial-tools (11.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 11.0

#708 Syncing from upstream OCA/account-financial-tools (12.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 12.0

#709 Syncing from upstream OCA/account-financial-tools (13.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 13.0

#710 Syncing from upstream OCA/account-financial-tools (14.0)
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
Labels: 14.0

#713 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: 14.0

#714 Syncing from upstream OCA/account-financial-tools (15.0)
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: 15.0

#715 Syncing from upstream OCA/account-financial-tools (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
Labels: 14.0
