Repository brain-tec/account-financial-tools, pull requests merged in 2021-09, with the labels that each got.

#683 Syncing from upstream OCA/account-financial-tools (13.0)
  account_asset_management/__manifest__.py
  account_asset_management/models/account_asset.py
Labels: 13.0

#684 Syncing from upstream OCA/account-financial-tools (13.0)
  account_maturity_date_default/README.rst
  account_maturity_date_default/__init__.py
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move_line.py
  account_maturity_date_default/readme/CONTRIBUTORS.rst
  account_maturity_date_default/readme/DESCRIPTION.rst
  account_maturity_date_default/static/description/icon.png
  account_maturity_date_default/static/description/index.html
  account_maturity_date_default/tests/__init__.py
  account_maturity_date_default/tests/test_account_move.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_maturity_date_default/odoo/addons/account_maturity_date_default
  setup/account_maturity_date_default/setup.py
Labels: 13.0

#680 Updating from latest OCA 13.0
  account_asset_management/__manifest__.py
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_move.py
  account_asset_management/wizard/account_asset_remove.py
  account_maturity_date_default/README.rst
  account_maturity_date_default/__init__.py
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move_line.py
  account_maturity_date_default/readme/CONTRIBUTORS.rst
  account_maturity_date_default/readme/DESCRIPTION.rst
  account_maturity_date_default/static/description/icon.png
  account_maturity_date_default/static/description/index.html
  account_maturity_date_default/tests/__init__.py
  account_maturity_date_default/tests/test_account_move.py
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/views/account_move_view.xml
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_maturity_date_default/odoo/addons/account_maturity_date_default
  setup/account_maturity_date_default/setup.py
Labels: 13.0.project_mi_465

#685 Syncing from upstream OCA/account-financial-tools (12.0)
  account_move_line_drilldown/README.rst
  account_move_line_drilldown/__init__.py
  account_move_line_drilldown/__manifest__.py
  account_move_line_drilldown/hooks.py
  account_move_line_drilldown/i18n/account_move_line_drilldown.pot
  account_move_line_drilldown/models/__init__.py
  account_move_line_drilldown/models/account_account.py
  account_move_line_drilldown/models/account_group.py
  account_move_line_drilldown/models/account_move_line.py
  account_move_line_drilldown/readme/CONFIGURE.rst
  account_move_line_drilldown/readme/CONTRIBUTORS.readme
  account_move_line_drilldown/readme/DESCRIPTION.rst
  account_move_line_drilldown/readme/INSTALL.rst
  account_move_line_drilldown/readme/USAGE.rst
  account_move_line_drilldown/static/description/drilldown_pivot.png
  account_move_line_drilldown/static/description/drilldown_tree.png
  account_move_line_drilldown/static/description/icon.png
  account_move_line_drilldown/static/description/index.html
  account_move_line_drilldown/tests/__init__.py
  account_move_line_drilldown/tests/test_account_move_line_drilldown.py
  account_move_line_drilldown/views/account_move_line_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_drilldown/odoo/addons/account_move_line_drilldown
  setup/account_move_line_drilldown/setup.py
Labels: 12.0

#687 Syncing from upstream OCA/account-financial-tools (14.0)
  account_check_deposit/i18n/pt.po
  account_menu/i18n/pt.po
Labels: 14.0

#688 Syncing from upstream OCA/account-financial-tools (12.0)
  account_invoice_constraint_chronology/i18n/it.po
Labels: 12.0

#689 Syncing from upstream OCA/account-financial-tools (13.0)
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move.py
  account_maturity_date_default/tests/test_account_move.py
Labels: 13.0

#690 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 14.0

#691 Syncing from upstream OCA/account-financial-tools (14.0)
  account_invoice_constraint_chronology/i18n/fr.po
Labels: 14.0

#692 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 14.0

#693 Syncing from upstream OCA/account-financial-tools (12.0)
  account_invoice_constraint_chronology/i18n/it.po
Labels: 12.0

#694 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
  account_asset_management/wizard/account_asset_remove.py
Labels: 14.0
