Repository brain-tec/account-financial-tools, pull requests merged in 2021-11, with the labels that each got.

#723 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_account_prepare_anglo_saxon_out_lines_hook/odoo/addons/stock_account_prepare_anglo_saxon_out_lines_hook
  setup/stock_account_prepare_anglo_saxon_out_lines_hook/setup.py
  stock_account_prepare_anglo_saxon_out_lines_hook/README.rst
  stock_account_prepare_anglo_saxon_out_lines_hook/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
  stock_account_prepare_anglo_saxon_out_lines_hook/i18n/stock_account_prepare_anglo_saxon_out_lines_hook.pot
  stock_account_prepare_anglo_saxon_out_lines_hook/models/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move_line.py
  stock_account_prepare_anglo_saxon_out_lines_hook/static/description/icon.png
Labels: 14.0

#724 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/views/account_move_view.xml
Labels: 14.0

#725 Syncing from upstream OCA/account-financial-tools (12.0)
  account_move_template/i18n/it.po
Labels: 12.0

#726 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
Labels: 14.0

#727 Syncing from upstream OCA/account-financial-tools (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 14.0

#728 Syncing from upstream OCA/account-financial-tools (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 15.0

#730 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_sale_info/odoo/addons/account_move_line_sale_info
  setup/account_move_line_sale_info/setup.py
Labels: 14.0

#732 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/readme/CONFIGURE.rst
  account_move_line_sale_info/readme/CONTRIBUTORS.rst
  account_move_line_sale_info/readme/DESCRIPTION.rst
  account_move_line_sale_info/readme/USAGE.rst
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/static/description/index.html
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_sale_info/odoo/addons/account_move_line_sale_info
  setup/account_move_line_sale_info/setup.py
Labels: 15.0

#733 Syncing from upstream OCA/account-financial-tools (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .t2d.yml
  LICENSE
  README.md
  account_cash_basis_group_base_line/__manifest__.py
  account_chart_update/__manifest__.py
  account_fiscal_year/README.rst
  account_fiscal_year/__manifest__.py
  account_fiscal_year/static/description/index.html
  account_invoice_constraint_chronology/__manifest__.py
  account_loan/__manifest__.py
  account_move_line_purchase_info/__manifest__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_used_currency/__manifest__.py
  account_netting/__manifest__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  base_vat_optional_vies/tests/test_res_partner.py
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
Labels: 13.0

#737 Syncing from upstream OCA/account-financial-tools (13.0)
  account_journal_lock_date/i18n/es.po
  account_menu/i18n/sk_SK.po
Labels: 13.0

#738 Merging 13.0 into 13.0.project_MI_465
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .t2d.yml
  LICENSE
  README.md
  account_cash_basis_group_base_line/__manifest__.py
  account_chart_update/__manifest__.py
  account_fiscal_year/README.rst
  account_fiscal_year/__manifest__.py
  account_fiscal_year/static/description/index.html
  account_invoice_constraint_chronology/__manifest__.py
  account_journal_lock_date/i18n/es.po
  account_loan/__manifest__.py
  account_menu/i18n/sk_SK.po
  account_move_line_purchase_info/__manifest__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_used_currency/__manifest__.py
  account_netting/__manifest__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  base_vat_optional_vies/tests/test_res_partner.py
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
Labels: 13.0.project_mi_465

#739 Syncing from upstream OCA/account-financial-tools (12.0)
  account_group_menu/i18n/fr.po
Labels: 12.0

#740 Syncing from upstream OCA/account-financial-tools (14.0)
  account_check_deposit/i18n/fr.po
Labels: 14.0
