Repository brain-tec/account-financial-tools, pull requests merged in 2022-08, with the labels that each got.

#894 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: 13.0

#895 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: 14.0

#896 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: 15.0

#897 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/i18n/es_AR.po
Labels: 14.0

#899 Updating from latest OCA 13.0
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: 13.0.project_mi_465

#898 Updating from latest OCA 15.0
  README.md
  account_asset_management_menu/README.rst
  account_asset_management_menu/__init__.py
  account_asset_management_menu/__manifest__.py
  account_asset_management_menu/i18n/account_asset_management_menu.pot
  account_asset_management_menu/readme/CONFIGURATION.rst
  account_asset_management_menu/readme/CONTRIBUTORS.rst
  account_asset_management_menu/readme/DESCRIPTION.rst
  account_asset_management_menu/static/description/icon.png
  account_asset_management_menu/static/description/index.html
  account_asset_management_menu/views/menuitem.xml
  account_chart_update/__manifest__.py
  account_chart_update/wizard/wizard_chart_update.py
  base_vat_optional_vies/i18n/pt.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_asset_management_menu/odoo/addons/account_asset_management_menu
  setup/account_asset_management_menu/setup.py
Labels: 15.0.project_mi_465

#900 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  product_category_tax/__manifest__.py
  product_category_tax/models/product_category.py
  product_category_tax/models/product_product.py
  product_category_tax/models/product_template.py
  product_category_tax/tests/test_product_category_tax.py
Labels: 13.0

#902 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/demo/ir_sequence_demo.xml
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_sequence_concurrency.py
Labels: 14.0

#903 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  account_move_line_cumulated_balance/README.rst
  account_move_line_cumulated_balance/__init__.py
  account_move_line_cumulated_balance/__manifest__.py
  account_move_line_cumulated_balance/i18n/account_move_line_cumulated_balance.pot
  account_move_line_cumulated_balance/i18n/es.po
  account_move_line_cumulated_balance/models/__init__.py
  account_move_line_cumulated_balance/models/account_move_line.py
  account_move_line_cumulated_balance/readme/CONFIGURE.rst
  account_move_line_cumulated_balance/readme/CONTRIBUTORS.rst
  account_move_line_cumulated_balance/readme/DESCRIPTION.rst
  account_move_line_cumulated_balance/readme/ROADMAP.rst
  account_move_line_cumulated_balance/readme/USAGE.rst
  account_move_line_cumulated_balance/static/description/icon.png
  account_move_line_cumulated_balance/static/description/index.html
  account_move_line_cumulated_balance/tests/__init__.py
  account_move_line_cumulated_balance/tests/test_account_move_line_cumulated_balance.py
  account_move_line_cumulated_balance/views/account_move_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_cumulated_balance/odoo/addons/account_move_line_cumulated_balance
  setup/account_move_line_cumulated_balance/setup.py
Labels: 13.0

#904 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_number/i18n/hr.po
  account_fiscal_position_vat_check/i18n/hr.po
  account_menu/i18n/hr.po
  account_move_line_menu/i18n/hr.po
  account_move_name_sequence/i18n/hr.po
  account_move_print/i18n/hr.po
  account_netting/i18n/hr.po
  base_vat_optional_vies/i18n/hr.po
  product_category_tax/i18n/hr.po
Labels: 14.0

#905 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  account_move_line_cumulated_balance/README.rst
  account_move_line_cumulated_balance/__init__.py
  account_move_line_cumulated_balance/__manifest__.py
  account_move_line_cumulated_balance/i18n/account_move_line_cumulated_balance.pot
  account_move_line_cumulated_balance/i18n/es.po
  account_move_line_cumulated_balance/models/__init__.py
  account_move_line_cumulated_balance/models/account_move_line.py
  account_move_line_cumulated_balance/readme/CONFIGURE.rst
  account_move_line_cumulated_balance/readme/CONTRIBUTORS.rst
  account_move_line_cumulated_balance/readme/DESCRIPTION.rst
  account_move_line_cumulated_balance/readme/ROADMAP.rst
  account_move_line_cumulated_balance/readme/USAGE.rst
  account_move_line_cumulated_balance/static/description/icon.png
  account_move_line_cumulated_balance/static/description/index.html
  account_move_line_cumulated_balance/tests/__init__.py
  account_move_line_cumulated_balance/tests/test_account_move_line_cumulated_balance.py
  account_move_line_cumulated_balance/views/account_move_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_cumulated_balance/odoo/addons/account_move_line_cumulated_balance
  setup/account_move_line_cumulated_balance/setup.py
Labels: 13.0.project_mi_465
