Repository brain-tec/account-financial-tools, pull requests merged in 2022-01, with the labels that each got.

#751 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_management/i18n/ar.po
Labels: 14.0

#752 [MIG] account_menu: Migration to 15.0
  account_menu/README.rst
  account_menu/__init__.py
  account_menu/__manifest__.py
  account_menu/demo/res_groups.xml
  account_menu/i18n/account_menu.pot
  account_menu/i18n/fr.po
  account_menu/i18n/fr_FR.po
  account_menu/i18n/it.po
  account_menu/i18n/nl.po
  account_menu/i18n/pt.po
  account_menu/models/__init__.py
  account_menu/models/account_group.py
  account_menu/models/account_tag.py
  account_menu/models/account_tax_group.py
  account_menu/models/res_config_settings.py
  account_menu/readme/CONFIGURE.rst
  account_menu/readme/CONTRIBUTORS.rst
  account_menu/readme/DESCRIPTION.rst
  account_menu/readme/ROADMAP.rst
  account_menu/static/description/icon.png
  account_menu/static/description/index.html
  account_menu/views/menu.xml
  account_menu/views/res_config_settings_views.xml
  account_menu/views/view_account_account_template.xml
  account_menu/views/view_account_bank_statement.xml
  account_menu/views/view_account_chart_template.xml
  account_menu/views/view_account_fiscal_position_template.xml
  account_menu/views/view_account_group.xml
  account_menu/views/view_account_tag.xml
  account_menu/views/view_account_tax_group.xml
  account_menu/views/view_account_tax_template.xml
  account_menu/views/view_account_type.xml
  setup/account_menu/odoo/addons/account_menu
  setup/account_menu/setup.py
Labels: 15.0.project_mi_465

#753 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/i18n/sk_SK.po
Labels: 14.0

#754 Syncing from upstream OCA/account-financial-tools (12.0)
  account_coa_menu/i18n/tr.po
  account_menu/i18n/tr.po
Labels: 12.0

#755 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/README.rst
  account_asset_management/__manifest__.py
  account_asset_management/static/description/index.html
Labels: 14.0

#756 Syncing from upstream OCA/account-financial-tools (12.0)
  account_lock_date_update/i18n/fr.po
Labels: 12.0

#757 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
Labels: 15.0

#758 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/migrations/12.0.1.0.0/post-migration.py
Labels: 12.0

#759 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/views/account_asset.xml
Labels: 13.0

#760 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  account_document_reversal/README.rst
  account_document_reversal/__init__.py
  account_document_reversal/__manifest__.py
  account_document_reversal/i18n/account_document_reversal.pot
  account_document_reversal/i18n/hr.po
  account_document_reversal/i18n/pt.po
  account_document_reversal/models/__init__.py
  account_document_reversal/models/account.py
  account_document_reversal/models/account_bank_statement.py
  account_document_reversal/models/account_document_reversal.py
  account_document_reversal/models/account_move.py
  account_document_reversal/models/account_payment.py
  account_document_reversal/models/purchase.py
  account_document_reversal/models/sale.py
  account_document_reversal/readme/CONFIGURE.rst
  account_document_reversal/readme/CONTRIBUTORS.rst
  account_document_reversal/readme/DESCRIPTION.rst
  account_document_reversal/readme/USAGE.rst
  account_document_reversal/static/description/icon.png
  account_document_reversal/static/description/index.html
  account_document_reversal/tests/__init__.py
  account_document_reversal/tests/test_invoice_reversal.py
  account_document_reversal/tests/test_payment_reversal.py
  account_document_reversal/views/account_move_view.xml
  account_document_reversal/views/account_payment_view.xml
  account_document_reversal/views/account_view.xml
  account_document_reversal/wizard/__init__.py
  account_document_reversal/wizard/reverse_account_document.py
  account_document_reversal/wizard/reverse_account_document_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_document_reversal/odoo/addons/account_document_reversal
  setup/account_document_reversal/setup.py
Labels: 13.0

#762 Fixed issue with badly merged conflicting file
  account_document_reversal/i18n/account_document_reversal.pot
Labels: 13.0.project_mi_465

#764 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/migrations/12.0.1.0.0/pre-migration.py
Labels: 12.0

#765 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__init__.py
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/.gitkeep
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONFIGURE.rst
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/readme/USAGE.rst
  base_vat_optional_vies/static/description/icon.png
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_partner_view.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_vat_optional_vies/odoo/addons/base_vat_optional_vies
  setup/base_vat_optional_vies/setup.py
Labels: 15.0

#766 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/readme/CONTRIBUTORS.rst
  account_lock_to_date/readme/DESCRIPTION.rst
  account_lock_to_date/readme/USAGE.rst
  account_lock_to_date/security/ir.model.access.csv
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
  account_move_budget/README.rst
  account_move_budget/__init__.py
  account_move_budget/__manifest__.py
  account_move_budget/i18n/account_move_budget.pot
  account_move_budget/i18n/fr.po
  account_move_budget/models/__init__.py
  account_move_budget/models/account_move_budget.py
  account_move_budget/models/account_move_budget_line.py
  account_move_budget/readme/CONTRIBUTORS.rst
  account_move_budget/readme/DESCRIPTION.rst
  account_move_budget/readme/USAGE.rst
  account_move_budget/security/ir.model.access.csv
  account_move_budget/static/description/icon.png
  account_move_budget/static/description/index.html
  account_move_budget/views/account_move_budget_line_views.xml
  account_move_budget/views/account_move_budget_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_lock_to_date/odoo/addons/account_lock_to_date
  setup/account_lock_to_date/setup.py
  setup/account_move_budget/odoo/addons/account_move_budget
  setup/account_move_budget/setup.py
Labels: 14.0

#767 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/i18n/sv.po
Labels: 14.0

#769 Updating from latest OCA 15.0
  README.md
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__init__.py
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/.gitkeep
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONFIGURE.rst
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/readme/USAGE.rst
  base_vat_optional_vies/static/description/icon.png
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_partner_view.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_vat_optional_vies/odoo/addons/base_vat_optional_vies
  setup/base_vat_optional_vies/setup.py
Labels: 15.0.project_mi_465
