Repository brain-tec/account-financial-tools, pull requests merged in 2022-07, with the labels that each got.

#881 Updating from latest OCA 15.0
  README.md
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/views/account_move_line.xml
  account_move_template/i18n/es_AR.po
Labels: 15.0.project_mi_465

#882 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_reversal_choose_method/README.rst
  account_move_reversal_choose_method/__init__.py
  account_move_reversal_choose_method/__manifest__.py
  account_move_reversal_choose_method/i18n/account_move_reversal_choose_method.pot
  account_move_reversal_choose_method/readme/CONTRIBUTORS.rst
  account_move_reversal_choose_method/readme/DESCRIPTION.rst
  account_move_reversal_choose_method/static/description/icon.png
  account_move_reversal_choose_method/static/description/index.html
  account_move_reversal_choose_method/wizard/account_move_reversal_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_reversal_choose_method/odoo/addons/account_move_reversal_choose_method
  setup/account_move_reversal_choose_method/setup.py
Labels: 14.0

#883 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 14.0

#884 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: 14.0

#885 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_transfer/README.rst
  account_asset_transfer/i18n/account_asset_transfer.pot
  account_asset_transfer/models/account_asset.py
  account_asset_transfer/readme/CONTRIBUTORS.rst
  account_asset_transfer/readme/DESCRIPTION.rst
  account_asset_transfer/static/description/index.html
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_asset_transfer/views/account_asset.xml
  account_asset_transfer/wizard/account_asset_transfer.py
Labels: 14.0

#886 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: 15.0

#887 Syncing from upstream OCA/account-financial-tools (12.0)
  account_lock_date_update/i18n/it.po
  account_lock_to_date/i18n/it.po
Labels: 12.0

#888 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_menu/__manifest__.py
  account_menu/i18n/account_menu.pot
  account_menu/views/view_account_tax_group.xml
Labels: 14.0

#889 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/i18n/es_PA.po
  account_menu/i18n/fr.po
  account_menu/i18n/fr_FR.po
  account_menu/i18n/it.po
  account_menu/i18n/nl.po
  account_menu/i18n/pt.po
  account_menu/i18n/sk_SK.po
  account_menu/i18n/sl_SI.po
  account_menu/i18n/sv.po
Labels: 14.0

#890 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  product_category_tax/__manifest__.py
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: 15.0

#892 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_force_removal/__manifest__.py
  account_move_force_removal/tests/test_move.py
Labels: 14.0

#893 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_asset_management_menu/README.rst
  account_asset_management_menu/__init__.py
  account_asset_management_menu/__manifest__.py
  account_asset_management_menu/i18n/account_asset_management_menu.pot
  account_asset_management_menu/readme/CONFIGURATION.rst
  account_asset_management_menu/readme/CONTRIBUTORS.rst
  account_asset_management_menu/readme/DESCRIPTION.rst
  account_asset_management_menu/static/description/icon.png
  account_asset_management_menu/static/description/index.html
  account_asset_management_menu/views/menuitem.xml
  base_vat_optional_vies/i18n/pt.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_asset_management_menu/odoo/addons/account_asset_management_menu
  setup/account_asset_management_menu/setup.py
Labels: 15.0
