Repository brain-tec/account-financial-tools, pull requests merged in 2022-04, with the labels that each got.

#805 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/models/account_move.py
Labels: 14.0

#807 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/readme/CONFIGURE.rst
  account_move_fiscal_year/readme/CONTRIBUTORS.rst
  account_move_fiscal_year/readme/DESCRIPTION.rst
  account_move_fiscal_year/readme/INSTALL.rst
  account_move_fiscal_year/readme/USAGE.rst
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_fiscal_year/odoo/addons/account_move_fiscal_year
  setup/account_move_fiscal_year/setup.py
Labels: 14.0

#808 Syncing from upstream OCA/account-financial-tools (14.0)
  account_move_fiscal_year/i18n/am.po
Labels: 14.0

#812 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_asset_management/i18n/it.po
  account_chart_update/i18n/it.po
  account_check_deposit/i18n/it.po
  account_journal_lock_date/i18n/it.po
  account_loan/i18n/it.po
  account_lock_date_update/i18n/it.po
  account_menu/i18n/it.po
  account_move_fiscal_month/README.rst
  account_move_fiscal_month/__init__.py
  account_move_fiscal_month/__manifest__.py
  account_move_fiscal_month/i18n/account_move_fiscal_month.pot
  account_move_fiscal_month/i18n/am.po
  account_move_fiscal_month/i18n/ca.po
  account_move_fiscal_month/i18n/de.po
  account_move_fiscal_month/i18n/es.po
  account_move_fiscal_month/i18n/es_EC.po
  account_move_fiscal_month/i18n/fr.po
  account_move_fiscal_month/i18n/gl.po
  account_move_fiscal_month/i18n/hr.po
  account_move_fiscal_month/i18n/hr_HR.po
  account_move_fiscal_month/i18n/it.po
  account_move_fiscal_month/i18n/nl.po
  account_move_fiscal_month/i18n/pt.po
  account_move_fiscal_month/i18n/pt_BR.po
  account_move_fiscal_month/i18n/pt_PT.po
  account_move_fiscal_month/i18n/sl.po
  account_move_fiscal_month/i18n/tr_TR.po
  account_move_fiscal_month/models/__init__.py
  account_move_fiscal_month/models/account_move.py
  account_move_fiscal_month/models/account_move_line.py
  account_move_fiscal_month/readme/CONFIGURE.rst
  account_move_fiscal_month/readme/CONTRIBUTORS.rst
  account_move_fiscal_month/readme/DESCRIPTION.rst
  account_move_fiscal_month/static/description/icon.png
  account_move_fiscal_month/static/description/index.html
  account_move_fiscal_month/tests/__init__.py
  account_move_fiscal_month/tests/test_account_move_fiscal_month.py
  account_move_fiscal_month/views/account_move.xml
  account_move_fiscal_month/views/account_move_line.xml
  account_move_template/i18n/it.po
  account_netting/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_fiscal_month/odoo/addons/account_move_fiscal_month
  setup/account_move_fiscal_month/setup.py
  test-requirements.txt
Labels: 14.0

#813 Syncing from upstream OCA/account-financial-tools (13.0)
  account_chart_update/i18n/es.po
Labels: 13.0

#814 Syncing from upstream OCA/account-financial-tools (14.0)
  account_chart_update/i18n/es.po
Labels: 14.0

#815 Syncing from upstream OCA/account-financial-tools (12.0)
  account_lock_date_update/i18n/it.po
  account_lock_to_date/i18n/it.po
Labels: 12.0

#816 Syncing from upstream OCA/account-financial-tools (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/tests/test_asset_management_xls.py
  account_asset_management/wizard/account_asset_remove.py
  account_asset_transfer/__manifest__.py
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year/data/date_range_type.xml
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/i18n/fr_FR.po
  account_fiscal_year/i18n/it.po
  account_fiscal_year/i18n/nl.po
  account_fiscal_year/security/ir.model.access.csv
  account_journal_lock_date/__manifest__.py
  account_journal_lock_date/tests/test_journal_lock_date.py
Labels: 14.0

#817 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/i18n/es.po
  account_group_menu/i18n/es.po
Labels: 12.0

#821 [13.0][FIX] Pre commit fails with "AttributeError: module 'collections' has no attribute 'MutableSet
  .github/workflows/pre-commit.yml
  account_chart_update/i18n/es.po
Labels: 13.0.project_mi_465

#824 Syncing from upstream OCA/account-financial-tools (15.0)
  account_asset_management/i18n/es_AR.po
Labels: 15.0
