Repository brain-tec/account-financial-tools, pull requests merged in 2022-05, with the labels that each got.

#825 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_sequence_option/README.rst
  account_sequence_option/__manifest__.py
  account_sequence_option/readme/CONTRIBUTORS.rst
  account_sequence_option/static/description/index.html
  account_sequence_option/tests/test_account_sequence_option.py
  account_sequence_option/views/account_move_views.xml
Labels: 14.0

#826 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_asset_management/__manifest__.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/tests/test_asset_management_xls.py
Labels: 15.0

#830 Syncing from upstream OCA/account-financial-tools (13.0)
  account_asset_management/i18n/es.po
  account_asset_management_menu/i18n/es.po
Labels: 13.0

#832 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_chart_update/i18n/es_AR.po
  account_move_force_removal/__manifest__.py
  account_move_force_removal/i18n/account_move_force_removal.pot
  account_move_force_removal/migrations/15.0.1.0.1/post-migration.py
  account_move_force_removal/models/account_move.py
  account_move_force_removal/security/account_move_force_removal_security.xml
  account_move_force_removal/tests/test_move.py
Labels: 15.0

#833 Syncing from upstream OCA/account-financial-tools (15.0)
  account_chart_update/i18n/es_AR.po
Labels: 15.0

#835 Updating from latest OCA 13.0
  account_asset_management/i18n/es.po
  account_asset_management_menu/i18n/es.po
Labels: 13.0.project_mi_465

#837 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_management/i18n/es.po
Labels: 14.0

#838 Syncing from upstream OCA/account-financial-tools (15.0)
  account_asset_management/i18n/es.po
Labels: 15.0

#840 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_management/i18n/es.po
  account_loan/i18n/it.po
Labels: 14.0

#841 Syncing from upstream OCA/account-financial-tools (15.0)
  account_asset_management/i18n/es.po
  account_move_force_removal/migrations/15.0.1.0.1/post-migration.py
Labels: 15.0

#842 Syncing from upstream OCA/account-financial-tools (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  README.md
  account_loan/i18n/it.po
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/post_install.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/readme/DESCRIPTION.rst
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_name_sequence/odoo/addons/account_move_name_sequence
  setup/account_move_name_sequence/setup.py
Labels: 14.0

#843 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_move_line_tax_editable/README.rst
  account_move_line_tax_editable/__init__.py
  account_move_line_tax_editable/__manifest__.py
  account_move_line_tax_editable/i18n/account_move_line_tax_editable.pot
  account_move_line_tax_editable/i18n/de.po
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/i18n/es_EC.po
  account_move_line_tax_editable/i18n/fr.po
  account_move_line_tax_editable/i18n/hr.po
  account_move_line_tax_editable/i18n/pt.po
  account_move_line_tax_editable/i18n/tr_TR.po
  account_move_line_tax_editable/models/__init__.py
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/readme/CONTRIBUTORS.rst
  account_move_line_tax_editable/readme/DESCRIPTION.rst
  account_move_line_tax_editable/static/description/icon.png
  account_move_line_tax_editable/static/description/index.html
  account_move_line_tax_editable/tests/__init__.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
  account_move_line_tax_editable/views/account_move.xml
  account_move_line_tax_editable/views/account_move_line.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_tax_editable/odoo/addons/account_move_line_tax_editable
  setup/account_move_line_tax_editable/setup.py
Labels: 15.0

#844 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_loan/i18n/it.po
  account_move_name_sequence/README.rst
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/post_install.py
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/views/account_journal.xml
Labels: 14.0

#845 Syncing from upstream OCA/account-financial-tools (13.0)
  account_chart_update/i18n/es.po
  account_fiscal_month/i18n/es.po
  account_loan/i18n/es.po
Labels: 13.0

#846 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_chart_update/i18n/es.po
  account_loan/i18n/it.po
  account_move_template/tests/test_account_move_template.py
Labels: 14.0

#847 Syncing from upstream OCA/account-financial-tools (14.0)
  account_chart_update/i18n/es.po
Labels: 14.0

#848 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  account_chart_update/i18n/es.po
  account_journal_lock_date/i18n/es.po
  account_move_line_tax_editable/i18n/es.po
  account_netting/__manifest__.py
  account_netting/wizards/account_move_make_netting.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
Labels: 13.0

#849 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_management/i18n/it.po
  account_chart_update/i18n/es.po
  account_check_deposit/i18n/it.po
Labels: 14.0

#850 Syncing from upstream OCA/account-financial-tools (15.0)
  account_chart_update/i18n/es_AR.po
Labels: 15.0

#851 Merging 15.0 into 15.0.project_MI_465
  README.md
  account_asset_management/i18n/es.po
  account_chart_update/i18n/es_AR.po
  account_move_force_removal/migrations/15.0.1.0.1/post-migration.py
  account_move_line_tax_editable/README.rst
  account_move_line_tax_editable/__init__.py
  account_move_line_tax_editable/__manifest__.py
  account_move_line_tax_editable/i18n/account_move_line_tax_editable.pot
  account_move_line_tax_editable/i18n/de.po
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/i18n/es_EC.po
  account_move_line_tax_editable/i18n/fr.po
  account_move_line_tax_editable/i18n/hr.po
  account_move_line_tax_editable/i18n/pt.po
  account_move_line_tax_editable/i18n/tr_TR.po
  account_move_line_tax_editable/models/__init__.py
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/readme/CONTRIBUTORS.rst
  account_move_line_tax_editable/readme/DESCRIPTION.rst
  account_move_line_tax_editable/static/description/icon.png
  account_move_line_tax_editable/static/description/index.html
  account_move_line_tax_editable/tests/__init__.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
  account_move_line_tax_editable/views/account_move.xml
  account_move_line_tax_editable/views/account_move_line.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_move_line_tax_editable/odoo/addons/account_move_line_tax_editable
  setup/account_move_line_tax_editable/setup.py
Labels: 15.0.project_mi_465

#853 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_lock_date_update/i18n/ca.po
  account_lock_date_update/i18n/es.po
  account_move_name_sequence/README.rst
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/readme/DESCRIPTION.rst
  account_move_name_sequence/static/description/index.html
Labels: 14.0

#854 Syncing from upstream OCA/account-financial-tools (15.0)
  account_fiscal_year/i18n/es.po
  account_lock_date_update/i18n/es.po
Labels: 15.0

#856 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/res_partner.py
Labels: 14.0

#857 Syncing from upstream OCA/account-financial-tools (13.0)
  README.md
  product_category_tax/__manifest__.py
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: 13.0

#858 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_move_name_sequence/README.rst
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
  product_category_tax/__manifest__.py
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: 14.0
