Repository brain-tec/account-financial-tools, pull requests merged in 2022-06, with the labels that each got.

#860 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__init__.py
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/__init__.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/models/account_move_line.py
  account_journal_general_sequence/readme/CONFIGURE.rst
  account_journal_general_sequence/readme/CONTRIBUTORS.rst
  account_journal_general_sequence/readme/DESCRIPTION.rst
  account_journal_general_sequence/readme/USAGE.rst
  account_journal_general_sequence/security/ir.model.access.csv
  account_journal_general_sequence/static/description/icon.png
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/__init__.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/views/account_move.xml
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_general_sequence/wizards/__init__.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard_views.xml
  account_move_template/__manifest__.py
  account_move_template/wizard/account_move_template_run.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_journal_general_sequence/odoo/addons/account_journal_general_sequence
  setup/account_journal_general_sequence/setup.py
Labels: 14.0

#861 Syncing from upstream OCA/account-financial-tools (12.0)
  account_group_menu/i18n/da.po
Labels: 12.0

#863 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_chart_update/__manifest__.py
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__init__.py
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/__init__.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/models/account_move_line.py
  account_journal_general_sequence/readme/CONFIGURE.rst
  account_journal_general_sequence/readme/CONTRIBUTORS.rst
  account_journal_general_sequence/readme/DESCRIPTION.rst
  account_journal_general_sequence/readme/INSTALL.rst
  account_journal_general_sequence/readme/USAGE.rst
  account_journal_general_sequence/security/ir.model.access.csv
  account_journal_general_sequence/static/description/icon.png
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/__init__.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/views/account_move.xml
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_general_sequence/wizards/__init__.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard_views.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_journal_general_sequence/odoo/addons/account_journal_general_sequence
  setup/account_journal_general_sequence/setup.py
Labels: 15.0

#864 Syncing from upstream OCA/account-financial-tools (12.0)
  account_asset_management/i18n/fr.po
Labels: 12.0

#867 Bugfixing tests account_move_line_used_currency
  account_move_line_used_currency/tests/test_account_move_line_used_currency.py
Labels: 13.0.project_mi_465

#866 Updating from latest OCA 13.0
  README.md
  product_category_tax/__manifest__.py
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: 13.0.project_mi_465

#871 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/test_res_partner.py
Labels: 14.0

#872 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/tests/test_res_partner.py
Labels: 15.0

#874 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  account_check_deposit/__manifest__.py
  account_check_deposit/migrations/13.0.1.2.0/noupdate_changes.xml
  account_check_deposit/migrations/13.0.1.2.0/post-migration.py
Labels: 13.0.project_mi_465

#875 Syncing from upstream OCA/account-financial-tools (15.0)
  account_move_template/i18n/es_AR.po
Labels: 15.0

#876 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_lock_date/i18n/fr.po
  account_lock_date_update/i18n/fr.po
  base_vat_optional_vies/i18n/fr.po
Labels: 14.0

#877 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/views/account_move_line.xml
Labels: 15.0

#878 Syncing from upstream OCA/account-financial-tools (14.0)
  account_lock_date_update/i18n/fr.po
  base_vat_optional_vies/i18n/fr.po
Labels: 14.0

#879 Syncing from upstream OCA/account-financial-tools (14.0)
  account_journal_general_sequence/i18n/hr.po
Labels: 14.0
