Repository brain-tec/account-financial-tools, pull requests merged in 2024-10, with the labels that each got.

#1613 Syncing from upstream OCA/account-financial-tools (17.0)
  README.md
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/i18n/es.po
  account_move_line_sale_info/i18n/es_AR.po
  account_move_line_sale_info/i18n/it.po
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/pyproject.toml
  account_move_line_sale_info/readme/CONTRIBUTORS.md
  account_move_line_sale_info/readme/DESCRIPTION.md
  account_move_line_sale_info/readme/USAGE.md
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/static/description/index.html
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1614 Syncing from upstream OCA/account-financial-tools (8.0)
  account_asset_management/i18n/it.po
  account_balance_line/i18n/it.po
  account_check_deposit/i18n/it.po
  account_compute_tax_amount/i18n/it.po
  account_constraints/i18n/it.po
  account_cost_center/i18n/it.po
  account_move_reconcile_helper/i18n/it.po
  account_partner_required/i18n/it.po
  account_tax_analysis/i18n/it.po
Labels: 8.0

#1615 Syncing from upstream OCA/account-financial-tools (17.0)
  account_check_deposit/i18n/it.po
Labels: 17.0

#1616 Syncing from upstream OCA/account-financial-tools (17.0)
  account_check_deposit/i18n/it.po
Labels: 17.0

#1617 Syncing from upstream OCA/account-financial-tools (17.0)
  account_check_deposit/i18n/es_AR.po
Labels: 17.0

#1619 Syncing from upstream OCA/account-financial-tools (17.0)
  README.md
  account_move_template/README.rst
  account_move_template/__manifest__.py
  account_move_template/models/account_move_template.py
  account_move_template/static/description/index.html
  account_move_template/tests/test_account_move_template_options.py
  account_move_template/wizard/account_move_template_run.py
Labels: 17.0

#1620 Syncing from upstream OCA/account-financial-tools (16.0)
  account_bank_statement_chatter/i18n/it.po
Labels: 16.0

#1621 Syncing from upstream OCA/account-financial-tools (14.0)
  README.md
  account_loan/README.rst
  account_loan/__manifest__.py
  account_loan/static/description/index.html
  account_loan/wizard/account_loan_post.py
Labels: 14.0

#1622 Syncing from upstream OCA/account-financial-tools (15.0)
  README.md
  account_loan/README.rst
  account_loan/__manifest__.py
  account_loan/static/description/index.html
  account_loan/wizard/account_loan_post.py
Labels: 15.0

#1623 Syncing from upstream OCA/account-financial-tools (16.0)
  README.md
  account_loan/README.rst
  account_loan/__manifest__.py
  account_loan/static/description/index.html
  account_loan/wizards/account_loan_post.py
Labels: 16.0

#1624 Syncing from upstream OCA/account-financial-tools (17.0)
  account_check_deposit/i18n/it.po
Labels: 17.0

#1625 Syncing from upstream OCA/account-financial-tools (17.0)
  README.md
  account_check_deposit/i18n/it.po
  purchase_unreconciled/README.rst
  purchase_unreconciled/__init__.py
  purchase_unreconciled/__manifest__.py
  purchase_unreconciled/i18n/it.po
  purchase_unreconciled/i18n/purchase_unreconciled.pot
  purchase_unreconciled/models/__init__.py
  purchase_unreconciled/models/account_move_line.py
  purchase_unreconciled/models/company.py
  purchase_unreconciled/models/purchase_order.py
  purchase_unreconciled/models/res_config_settings.py
  purchase_unreconciled/pyproject.toml
  purchase_unreconciled/readme/CONTRIBUTORS.md
  purchase_unreconciled/readme/DESCRIPTION.md
  purchase_unreconciled/readme/USAGE.md
  purchase_unreconciled/security/ir.model.access.csv
  purchase_unreconciled/static/description/icon.png
  purchase_unreconciled/static/description/index.html
  purchase_unreconciled/tests/__init__.py
  purchase_unreconciled/tests/test_purchase_unreconciled.py
  purchase_unreconciled/views/purchase_order_view.xml
  purchase_unreconciled/views/res_config_settings_view.xml
  purchase_unreconciled/wizards/__init__.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1626 Syncing from upstream OCA/account-financial-tools (17.0)
  purchase_unreconciled/i18n/it.po
Labels: 17.0

#1627 Syncing from upstream OCA/account-financial-tools (18.0)
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
Labels: 18.0

#1629 Syncing from upstream OCA/account-financial-tools (17.0)
  purchase_unreconciled/i18n/it.po
Labels: 17.0

#1630 Syncing from upstream OCA/account-financial-tools (8.0)
  account_credit_control/i18n/it.po
Labels: 8.0

#1631 Syncing from upstream OCA/account-financial-tools (16.0)
  README.md
  account_chart_update/README.rst
  account_chart_update/__manifest__.py
  account_chart_update/static/description/index.html
  account_chart_update/wizard/wizard_chart_update.py
Labels: 16.0

#1632 18.0 mig account move name sequence
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/demo/account_journal_demo.xml
  account_move_name_sequence/demo/ir_sequence_demo.xml
  account_move_name_sequence/hooks.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/i18n/ar.po
  account_move_name_sequence/i18n/es.po
  account_move_name_sequence/i18n/fr.po
  account_move_name_sequence/i18n/hr.po
  account_move_name_sequence/i18n/it.po
  account_move_name_sequence/i18n/sl.po
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/pyproject.toml
  account_move_name_sequence/readme/CONFIGURE.md
  account_move_name_sequence/readme/CONTRIBUTORS.md
  account_move_name_sequence/readme/DESCRIPTION.md
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_incoming_supplier_invoice.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/tests/test_sequence_concurrency.py
  account_move_name_sequence/views/account_journal_views.xml
  account_move_name_sequence/views/account_move_views.xml
Labels: 18.0.project_ca_772
