Repository brain-tec/account-financial-tools, pull requests merged in 2024-12, with the labels that each got.

#1655 Syncing from upstream OCA/account-financial-tools (16.0)
  README.md
  account_chart_update/README.rst
  account_chart_update/__manifest__.py
  account_chart_update/static/description/index.html
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_loan/README.rst
  account_loan/__manifest__.py
  account_loan/models/account_loan_line.py
  account_loan/static/description/index.html
  account_move_budget/i18n/it.po
Labels: 16.0

#1656 Syncing from upstream OCA/account-financial-tools (16.0)
  README.md
  account_asset_management/README.rst
  account_asset_management/__manifest__.py
  account_asset_management/static/description/index.html
  account_asset_management/wizard/wiz_account_asset_report.xml
Labels: 16.0

#1657 Syncing from upstream OCA/account-financial-tools (14.0)
  account_account_constraint_code/i18n/it.po
  account_asset_batch_compute/i18n/it.po
  account_asset_from_expense/i18n/it.po
  account_asset_low_value/i18n/it.po
  account_asset_management_menu/i18n/it.po
  account_asset_number/i18n/it.po
  account_asset_stock_move/i18n/it.po
  account_asset_transfer/i18n/it.po
  account_cash_deposit/i18n/it.po
  account_journal_general_sequence/i18n/it.po
  account_move_default_journal/i18n/it.po
  account_move_force_removal/i18n/it.po
  account_move_line_menu/i18n/it.po
  account_move_line_repair_info/i18n/it.po
  account_move_line_tax_editable/i18n/it.po
  account_move_line_used_currency/i18n/it.po
  account_move_transfer_partner/i18n/it.po
  account_no_default/i18n/it.po
  account_reconcile_show_boolean/i18n/it.po
  account_spread_cost_revenue/i18n/it.po
  account_spread_cost_revenue_enhanced/i18n/it.po
  account_template_active/i18n/it.po
  product_category_tax/i18n/it.po
  stock_account_prepare_anglo_saxon_out_lines_hook/i18n/it.po
Labels: 14.0

#1658 Syncing from upstream OCA/account-financial-tools (14.0)
  account_asset_compute_batch/i18n/it.po
  account_lock_to_date/i18n/it.po
  account_move_line_check_number/i18n/it.po
  account_move_line_landed_cost_info/i18n/it.po
  account_move_line_sale_info/i18n/it.po
  account_move_print/i18n/it.po
  account_move_reversal_choose_method/i18n/it.po
Labels: 14.0

#1659 Syncing from upstream OCA/account-financial-tools (12.0)
  account_menu/i18n/it.po
Labels: 12.0

#1660 Syncing from upstream OCA/account-financial-tools (14.0)
  account_menu/i18n/it.po
Labels: 14.0

#1661 Syncing from upstream OCA/account-financial-tools (16.0)
  account_cash_deposit/i18n/it.po
  account_chart_update/i18n/it.po
  account_usability/i18n/it.po
Labels: 16.0

#1662 Syncing from upstream OCA/account-financial-tools (17.0)
  account_check_deposit/i18n/it.po
  account_usability/i18n/it.po
Labels: 17.0

#1663 Syncing from upstream OCA/account-financial-tools (18.0)
  account_usability/i18n/it.po
Labels: 18.0

#1664 Syncing from upstream OCA/account-financial-tools (16.0)
  README.md
  account_asset_management/README.rst
  account_asset_management/__manifest__.py
  account_asset_management/report/account_asset_report_xls.py
  account_asset_management/static/description/index.html
  account_invoice_constraint_chronology/README.rst
  account_invoice_constraint_chronology/__manifest__.py
  account_invoice_constraint_chronology/static/description/index.html
  account_invoice_constraint_chronology/tests/test_account_invoice_constraint_chronology.py
Labels: 16.0

#1665 Syncing from upstream OCA/account-financial-tools (18.0)
  README.md
  account_journal_restrict_mode/README.rst
  account_journal_restrict_mode/__init__.py
  account_journal_restrict_mode/__manifest__.py
  account_journal_restrict_mode/hooks.py
  account_journal_restrict_mode/i18n/account_journal_restrict_mode.pot
  account_journal_restrict_mode/i18n/es.po
  account_journal_restrict_mode/i18n/it.po
  account_journal_restrict_mode/models/__init__.py
  account_journal_restrict_mode/models/account_journal.py
  account_journal_restrict_mode/pyproject.toml
  account_journal_restrict_mode/readme/CONTRIBUTORS.md
  account_journal_restrict_mode/readme/DESCRIPTION.md
  account_journal_restrict_mode/readme/ROADMAP.md
  account_journal_restrict_mode/static/description/icon.png
  account_journal_restrict_mode/static/description/index.html
  account_journal_restrict_mode/tests/__init__.py
  account_journal_restrict_mode/tests/test_account_journal_restrict_mode.py
  account_move_post_date_user/README.rst
  account_move_post_date_user/__init__.py
  account_move_post_date_user/__manifest__.py
  account_move_post_date_user/i18n/account_move_post_date_user.pot
  account_move_post_date_user/i18n/it.po
  account_move_post_date_user/models/__init__.py
  account_move_post_date_user/models/account_move.py
  account_move_post_date_user/pyproject.toml
  account_move_post_date_user/readme/CONTRIBUTORS.md
  account_move_post_date_user/readme/DESCRIPTION.md
  account_move_post_date_user/static/description/icon.png
  account_move_post_date_user/static/description/index.html
  account_move_post_date_user/tests/__init__.py
  account_move_post_date_user/tests/test_account_move_post_date_user.py
  account_move_post_date_user/views/account_move.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1666 17.0 mig account asset number
  account_asset_number/README.rst
  account_asset_number/__init__.py
  account_asset_number/__manifest__.py
  account_asset_number/i18n/account_asset_number.pot
  account_asset_number/i18n/es.po
  account_asset_number/i18n/hr.po
  account_asset_number/i18n/it.po
  account_asset_number/models/__init__.py
  account_asset_number/models/account_asset.py
  account_asset_number/models/account_asset_profile.py
  account_asset_number/pyproject.toml
  account_asset_number/readme/CONFIGURE.md
  account_asset_number/readme/CONTRIBUTORS.md
  account_asset_number/readme/DESCRIPTION.md
  account_asset_number/report/__init__.py
  account_asset_number/report/account_asset_number_report.xml
  account_asset_number/report/account_asset_report_xls.py
  account_asset_number/static/description/icon.png
  account_asset_number/static/description/index.html
  account_asset_number/tests/__init__.py
  account_asset_number/tests/test_account_asset_number.py
  account_asset_number/views/account_asset_profile_views.xml
  account_asset_number/views/account_asset_views.xml
Labels: 17.0.project_go_755
